"""Recreate interview models

Revision ID: a0159ced2071
Revises: 004_question_progress
Create Date: 2026-08-01 18:08:04.415299
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0159ced2071'
down_revision: Union[str, None] = '004_question_progress'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('system_prompt_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_interview_categories_id'), 'interview_categories', ['id'], unique=False)
    op.create_index(op.f('ix_interview_categories_slug'), 'interview_categories', ['slug'], unique=True)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['interview_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('interview_session_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_flags_id'), 'interview_session_flags', ['id'], unique=False)
    op.drop_index('ix_llm_daily_usage_id', table_name='llm_daily_usage')
    op.drop_index('ix_llm_daily_usage_usage_date', table_name='llm_daily_usage')
    op.drop_index('ix_llm_daily_usage_user_id', table_name='llm_daily_usage')
    op.drop_table('llm_daily_usage')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.create_table('llm_daily_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('usage_date', sa.DATE(), nullable=False),
    sa.Column('request_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_daily_usage_user_id', 'llm_daily_usage', ['user_id'], unique=False)
    op.create_index('ix_llm_daily_usage_usage_date', 'llm_daily_usage', ['usage_date'], unique=False)
    op.create_index('ix_llm_daily_usage_id', 'llm_daily_usage', ['id'], unique=False)
    op.drop_index(op.f('ix_interview_session_flags_id'), table_name='interview_session_flags')
    op.drop_table('interview_session_flags')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interview_categories_slug'), table_name='interview_categories')
    op.drop_index(op.f('ix_interview_categories_id'), table_name='interview_categories')
    op.drop_table('interview_categories')
    # ### end Alembic commands ###
